name: Deploy via SSH

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Upload files via SCP
        uses: appleboy/scp-action@v0.1.7
        with:
          host: 150.232.1.80
          username: raojhibs
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          source: "."
          target: "/home/raojhibs/enom"

      - name: Run Laravel Commands
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: 150.232.1.80
          username: raojhibs
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            cd /home/raojhibs/enom
            composer install --no-dev --optimize-autoloader
            php artisan config:cache
            php artisan route:cache
            php artisan view:cache